services:
  - type: web
    name: carboncanopy-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
